### PR TITLE
Organization - part 1

### PR DESCRIPTION
**Pull request by retlehs**
* Move comments template into new folder
* Misc - make Discourse URL label obvious, remove helper note
* Move SSO and admin functions into separate files
* Switch from `register_uninstall_hook` to `uninstall.php`

work in progress, but done for tonight :sleeping:

### CODE REVIEW

**Comment by retlehs** [comment]
also removed a couple unused things, added the plugin uri, and changed the description to a nicer one from the README

**Comment by techAPJ** [comment]
Thanks @retlehs! :+1: 

I just merged #99, does this PR need any changes to accommodate that fix?

**Comment by retlehs** [comment]
nope, good to go

**Comment by techAPJ** [comment]
:heart:

**Pull request merged**
