### PR TITLE
Update Discourse post on WP post update

### LINKED ISSUE #151: Updating wp post should update discourse one?
I would like to know if I'm having some kind of error or it's just not happening. When I update a post in wordpress the same in Discourse isn't updated. I know the API can do it but it doesn't seem to happen. If it's working as intended then I'm sorry.

Thanks again!

### PR DESCRIPTION
**Pull request by tnorthcutt**
If a WP post is updated and has already been published
to Discourse, update the Discourse post with the new post
content or generated excerpt.

Closes #151

### CODE REVIEW

**Comment by tnorthcutt** [comment]
@retlehs hiya, any chance of getting some eyes on this for possible merge?

**Comment by retlehs** [comment]
looks good to me but won't have a chance to test. can @techAPJ or someone else confirm this works as expected before merge?

**Comment by techAPJ** [comment]
Looks good. Thanks! :+1:

**Comment by tnorthcutt** [comment]
Awesome, glad to see this merged! 

chuck-norris-thumbs-up-dodgeball

**Pull request merged**
