### PR TITLE
Allow choosing Discourse category per post

### PR DESCRIPTION
**Pull request by tnorthcutt**
Displays a select menu in Publish post metabox
containing Discourse categories

Cleans up code from
https://github.com/PaxInstruments/wp-discourse/commit/c8745d0671a62586bffa01611f68067c4239afe4

Submitted in place of https://github.com/discourse/wp-discourse/pull/175#issuecomment-173940826

### CODE REVIEW

**Comment by tnorthcutt** [comment]
@retlehs hiya, any chance of this getting merged? Let me know how I can help :smile:

**Comment by retlehs** [comment]
thanks & sorry for the delay! can someone else please confirm this works for them? i haven't had a chance to test this

/cc @techAPJ

**Comment by tnorthcutt** [comment]
@techAPJ any opportunity to test this?

**Comment by techAPJ** [comment]
@tnorthcutt Apologies for the delay! I will test and merge this PR this weekend.

**Comment by tnorthcutt** [comment]
@techAPJ Awesome! I'm working on two client projects using this extension right now and I will almost certainly have more coming, so if you guys ever want extra help maintaining this repo, I'd be happy to be added as a committer at some point.

**Comment by techAPJ** [comment]
Looks good. Thank You!

**Comment by techAPJ** [comment]
> I'm working on two client projects using this extension right now and I will almost certainly have more coming, so if you guys ever want extra help maintaining this repo, I'd be happy to be added as a committer at some point.

Great! Looking forward to see more PRs from you. :smile:

**Comment by tnorthcutt** [comment]
Awesome, thanks for getting this merged in!

**Pull request merged**
