### PR TITLE
WIP: Discourse Topic Map

### PR DESCRIPTION
**Pull request by scossar**
Working with @sudaraka94 to create a Discourse topic-map option for the wp-discourse plugin.

### CODE REVIEW

**Comment by jtbayly** [comment]
I'm getting an error attempting to use this with Ajax loading turned off:

`Fatal error
: Uncaught Error: Call to undefined function WPDiscourse\DiscourseComment\write_log() in /home/clearnot/staging/1/wp-content/plugins/wp-discourse/lib/discourse-comment.php:269 Stack trace: #0 /home/clearnot/staging/1/wp-includes/class-wp-hook.php(286): WPDiscourse\DiscourseComment\DiscourseComment->sync_comments(7721) #1 /home/clearnot/staging/1/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /home/clearnot/staging/1/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/clearnot/staging/1/wp-content/plugins/wp-discourse/lib/discourse-comment-formatter.php(52): do_action('wpdc_sync_disco...', 7721) #4 /home/clearnot/staging/1/wp-content/plugins/wp-discourse/lib/discourse-comment.php(325): WPDiscourse\DiscourseCommentFormatter\DiscourseCommentFormatter->format(7721) #5 /home/clearnot/staging/1/wp-includes/class-wp-hook.php(286): WPDiscourse\DiscourseComment\DiscourseComment->comments_template('/home/clearnot/...') #6 /home/clearnot/staging/1/wp-includes/plugin.php(203): WP_Hook- in
/home/clearnot/staging/1/wp-content/plugins/wp-discourse/lib/discourse-comment.php
on line
269`

If I turn Ajax loading on, I get nothing at all from the plugin. (This is all with "Use Discourse Comments" enabled)

**Comment by scossar** [comment]
Thanks for letting me know. That line shouldn't be there. It's a logging function that I use for development. This branch of the plugin isn't ready for production yet.  We'll try to get it merged to the beta branch by the end of the week. At that point, it would be great if you could try it out.

**Comment by jtbayly** [comment]
No problem. Will wait and try it out then.

**Comment by jtbayly** [comment]
“Since it's possible to link a WordPress post to an existing Discourse topic, this may not be a safe assumption.”

I think it’s probably too much opportunity for confusion to make that assumption.

**Comment by jtbayly** [comment]
I gather from your previous comment that this works, but simply is making more calls to the API than necessary. Under that assumption I'm going to check this out in its current form and give feedback unless I hear otherwise from you, @scossar

**Comment by jtbayly** [comment]
I'm guessing I just misunderstood what you meant above, but just in case, I figured I'd let you know I'm getting an error as follows when I try to run this version.

`Warning
: Invalid argument supplied for foreach() in
/...../wp-discourse/lib/discourse-topic-map-formatter.php
on line
80`

**Comment by jtbayly** [comment]
Awesome. Not surprised about WP 5.0 requiring work. 

Yeah, definitely not trying this on production. Just had a few minutes to mess around with my staging site and thought a quick test might be helpful. I'll wait for new commits, hopefully later this month.

**Comment by jtbayly** [comment]
Good job on getting ready for WP 5.0. Seems to be working well for me. Still hoping to see this feature added sometime soon. ;)

**Comment by jtbayly** [comment]
I don't want to be a pain, but I'm curious what the status is on this idea. Still planning to get it fixed up? Any idea on a timeline? I think the feature is a great idea.

**Comment by scossar** [comment]
I'm keeping this open for now. To properly implement it will require quite a few changes to the plugin though, so it may not get done for a while.

**Pull request closed without merging**
