### PR TITLE
Functionality for topic-map for wordpress

### PR DESCRIPTION
**Pull request by sudaraka94**

### CODE REVIEW

**Comment by scossar** [comment]
I'm looking at this now. I'm unsure about how it works. I was expecting https://github.com/procourse/wpdc-embed-topic-map to be a WordPress plugin. How is that code meant to be used?

**Comment by scossar** [comment]
If you can give me a couple of days to look at this, I'll have some ideas for you. I think it will be possible to do this with fewer changes to the WP Discourse plugin.

**Comment by scossar** [comment]
@sudaraka94 I like this a lot! I think it would be a good idea to include the topic-map in the wp-discourse plugin. It would be enabled with an option so that sites that don't want it can disable it. I've tried adding the code from your theme to the plugin and it's working for me. Is it ok if I make a few changes to your PR?

**Comment by sudaraka94** [comment]
Hi @scossar, If this can be added to the plugin that would be really awesome. Please do make changes. :) By the way I really like how you keep the wp-discourse plugin. One of the most readable php code I have ever seen and It is a great inspiration for me.

**Comment by scossar** [comment]
@sudaraka94 thanks! I've created a separate PR here: https://github.com/discourse/wp-discourse/pull/324. It's built on top of your sudaraka94-master branch. Maybe we should do the work there and close this PR.

Early next week I'll add some comments about what's going on in the PR.

**Comment by sudaraka94** [comment]
I will be closing the pr and moving to the new pr

**Pull request closed without merging**
