### PR TITLE
Add Composer support

### PR DESCRIPTION
**Pull request by retlehs**
This is a basic `composer.json` file which will let you publish the plugin to https://packagist.org/

### CODE REVIEW

**Comment by techAPJ** [comment]
:heart:

**Comment by retlehs** [comment]
awesome, thank you! can you submit the package on https://packagist.org/?

**Comment by techAPJ** [comment]
Okay, here's the package on Packagist: https://packagist.org/packages/discourse/wp-discourse

Also, added you as maintainer :)

**Comment by retlehs** [comment]
ty sir

**Pull request merged**
