### PR TITLE
Allow existing topics as comments

### PR DESCRIPTION
**Pull request by joebuhlig**

### CODE REVIEW

**Comment by scossar** [comment]
Thanks! I've been working on the exact same thing. You're implementation of it looks a lot simpler than mine. I'll take a closer look at it later today.

**Comment by joebuhlig** [comment]
Anything else you need from me on this one, @scossar?

**Comment by scossar** [comment]
There might be. It's the next thing I'm going to work on. Sorry for the
delay. I'll get back to you this week.

**Comment by scossar** [comment]
Sorry I haven't looked at this yet. A change has been requested to improve the efficiency with which the plugin pulls content from Discourse. I have to deal with that first.

I'm also about to change the Publish to Discourse meta box to look like this:

screenshot 2017-04-18 18 03 05

screenshot 2017-04-18 18 03 53

I need to look at how you are linking existing topics to WordPress posts and see if I can integrate it with the new metabox.

**Comment by joebuhlig** [comment]
I like the mockup. 👍 

This PR doesn't handle any of the data pulling from Discourse. It simply changes the URL called to get the data. 

From what I can tell, you would need to change the UI to accommodate this PR but other than that it should be fine.

**Comment by scossar** [comment]
Thanks for this! Existing Discourse topics can now be linked to WordPress posts. The code for that is largely based on your PR.

**Pull request closed without merging**
