### PR TITLE
Use Discourse instance as a SSO provider

### PR DESCRIPTION
**Pull request by iamntz**
Implemented the SSO functionality as discussed [here](https://meta.discourse.org/t/using-discourse-as-a-sso-client/32974/28?u=iamntz).

### What is this?
As its name states, will allow you to use a Discourse instance as a SSO provider. It works as follow:

1. If you don't have an account on WP, a new account will be created (although I'm not sure what's happening if you don't have an account on discourse...) and this new account will be linked to your discourse account.
1. if you do have an account on WP, discourse user will be linked to current user;

Clearly enough, discourse user info will be used to fill the WP user data, in order to mantain some kind of sync.

### How to use
You must fill discourse URL & SSO secret, then tick the `Enable Discourse SSO` & `Add "Login with Discourse" on the login form` checkboxes.

This also implements a shortcode and also provides a functions & some hooks that can be used by developers.

Shortcode can be used either simple : `[discourse_sso_client]` or with params, to allow customizing default anchor texts:

```
[discourse_sso_client login="Login to discourse" link="Link your account to discourse"]
```

#### Filters

```
apply_filters( 'discourse/sso/client/login_anchor', $anchor, $sso_login_url, $options, $discourse_options );
```
Allows you to alter default login anchor (i.e. if you want to use the shortcode in multiple place and you don't want to add the attributes every single time).

```
$updated_user = apply_filters( 'discourse/sso/client/updated_user', $updated_user, $query );
```
Allows you to change what data is saved from discourse payload to user meta.

```
$redirect_to = apply_filters( 'discourse/sso/client/redirect_after_login', $query['return_sso_url'] );
```
Allows you to specify a redirect url after successful  auth.

As a developer, you can also use `get_discourse_sso_url()` to get... well, the sso url.

### Quirks, issues & stuff

- Discourse doesn't send on SSO payload either an user is blocked or not, hence a blocked user will be able to log in to WP

### CODE REVIEW

**Comment by rmbolger** [comment]
@iamntz Really looking forward to this. Thanks for putting in the time/effort.

**Comment by scossar** [comment]
It's great that you're doing this. I don't have much time to look at it until early next week, but I'll do it then.

**Comment by scossar** [comment]
I'm trying this out now. It seems really good. There's an issue with the checkboxes on the options page not being validated, but I want to rework the `SettingsValidator` class so that we don't have to create a new validation function for every checkbox. I'll do that today or tomorrow.

Should logout be synced between WordPress and Discourse when someone logs into WordPress through Discourse? It seems there could be a risk that people will forget that by clicking 'Login through Discourse' that they have left themselves logged into the forum when the log out of the WordPress site.

**Comment by iamntz** [comment]
> Should logout be synced between WordPress and Discourse
Hmmm, good question.

Wonder how it works the other way around (i.e. if you're using WP as a sso provider and you log out from WP, you're also logged out from the forum?).

**Comment by scossar** [comment]
Yes, it's doing it here:
https://github.com/discourse/wp-discourse/blob/beta/lib/discourse-sso.php#L213

It's checking that the 'enable-sso' option is set. What would happen if it also checked for the sso option that you have added?

**Comment by iamntz** [comment]
Yup, good point. But this log out process shouldn't be handled by the sso provider?

**Comment by scossar** [comment]
Does it work?

Maybe the code needs to be moved around a bit so that sharing the function
makes more sense. Also, maybe the discousrse_user_id that's used in that
function could be saved as user_metadata instead of getting it on every
logout.

**Comment by scossar** [comment]
> But this log out process shouldn't be handled by the sso provider?

Yeah, you might be right. Depending on the use case, being automatically logged out of Discourse could be unexpected.

**Comment by iamntz** [comment]
I strongly believe that the SSO provider should decide if an user should be kicked out or not, not the other way around. So if there is a check, that should be on either an user is logged in on Discourse

Think of this usecase (that i'm currently using): one forum, multiple blogs. You may want to log out of one, but keep the other logged in.

**Comment by scossar** [comment]
Yeah, I was just thinking about how it could be used to run scheduling software for a Discourse forum on a WordPress site. People wouldn't want to be logged out of the forum after they signed up for something. 

For doing something like setting up schedules, or selling tickets, would it be possible to generate a login link to a specific wordpress page that could be included in a Discourse post?

**Comment by iamntz** [comment]
> For doing something like setting up schedules, or selling tickets, would it be possible to generate a login link to a specific wordpress page that could be included in a Discourse post?

I'm not sure I follow, could you elaborate a bit?

**Comment by scossar** [comment]
So that something like this would work:
- the user is logged into Discourse
- they click on a link in a Discourse post that logs them into a WordPress site and brings them to a specific page

It would make it possible to use WordPress to add some functionality to a Discourse forum - like selling tickets or booking appointments.

**Comment by iamntz** [comment]
Well, you have shortcodes for this. After you're logged in, you're redirected on the current page.

So, imagine this scenario:

1. Assuming you have woo commerce, EDD or whatever;
1. You're on a product page
1. Click on _Login with Discourse_
1. You're redirected to your Discourse instance;
1. SSO magic is happening;
1. If you didn't had an account, an account is created and if you had an account, then you're logged in;
1. You're redirected to the product page from the step 2.

Something that I missed? :)

**Comment by scossar** [comment]
@retlehs do you have any time to look at this PR?

**Comment by iamntz** [comment]
@retlehs happy new year! 🎆

**Comment by retlehs** [comment]
won't have time in the foreseeable future to review this, so if it works as expected then :shipit:

**Comment by scossar** [comment]
I looked at this some more. There is a problem with the way it is authenticating users on WordPress. The problem is that it isn't setting a unique, time-limited nonce for each SSO request. It needs to do this so that the response that is returned from Discourse can't be reused by anyone in the future. The way it is now, the response that's returned by Discourse can be used by anyone at anytime to log into the WordPress site as the user who the response was generated for. I think this means that it is vulnerable to a 'replay attack.'

Here's an example:
When I click on the 'Login through Discourse' link on my site, I'm redirected to Discourse, I go through the login process, and am then redirected back to WordPress and logged in. The query string that is used to authenticate me on WordPress is saved to my browser's history and can be used by anyone at any time to log into the WordPress site as me.

What needs to happen instead is that when a user visits a specific URL on the WordPress site, possibly `example.com/login`, WordPress will generate and save a nonce, generate the Discourse sso_login URL, and redirect to it. When WordPress receives the response from Discourse, it will verify the signature and verify and delete the nonce before logging in the user. Login links can be created to specific pages by including a 'redirect_to' parameter with the login link.

I've done some quick tests with this and it seems to work. There is an issue with logging in directly to WordPress admin pages that might be difficult to fix.

More info:
It needs to do what's outlined in this topic, but with Discourse, instead of WordPress, as the authenticator: https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045
Take note of this section in the topic:

> Security concerns
> 
> The nonce (one time token) will expire automatically after 10 minutes. This means that as soon as the user is redirected to your site they have 10 minutes to log in / create a new account.
> 
> The protocol is safe against replay attacks as nonce may only be used once.
> 

This topic outlines using Discourse as the SSO provider: https://meta.discourse.org/t/using-discourse-as-a-sso-provider/32974. It's important that the `nonce` is a real nonce (number used once) - it links to this page for the nonce definition: https://en.wikipedia.org/wiki/Cryptographic_nonce. This is different than a WordPress nonce.

**Comment by iamntz** [comment]
Hmmm, good point. I think that WP have a time-based nonce, but I'm not sure. Let's find out :)

**Comment by iamntz** [comment]
Alright, I've added a custom implementation of the wp nonce (a wrapper, really, with a custom timing).

The nonce lifetime is 600 seconds, but can be overriden by a very determined site owner:

`$nonce_life = apply_filters( 'discourse/nonce_life', 600 );`

I extracted the nonce functionality into `utilities` class, in case we later need it in other places.

**Comment by iamntz** [comment]
Any progress on reviewing this?

**Comment by scossar** [comment]
Yes, sorry for the delay. I'll still think that the SSO request needs to be generated by WordPress after the user clicks on a link. I think the way it's set up now will fail if the SSO link is on a cached page. It also doesn't allow a link to be embedded on Discourse that will directly log a user into a WordPress site. Possibly we have different use cases in mind.
I've taken the logic from your PR and reworked it into something that does what I'm talking about. There could be some problems with the way I'm approaching this. It would be great if you could look at my work and then we can figure out which way to approach this. I'll have something ready later today or early tomorrow.

**Comment by iamntz** [comment]
Ah! I think I know what you mean. We should have something like `myblog.com/auth-discourse`, and that should deal with everything else, right?

**Comment by scossar** [comment]
Yes. I've got it set up so that making a request to `myblog.com/sso?sso_redirect=/some-blog-page`  generates the sso_url on WordPress and redirects to it. That way the SSO link can be added either to WordPress or Discourse.

The code is here: https://github.com/scossar/wp-discourse/tree/beta-external-sso. It has no validation or sanitization yet, so it's not passing the code sniffer.

I've added an option to sync existing accounts by email address.  That's not really safe to use if the email address is allowed to be edited on WordPress, but it fixes the problem that occurs when users who have existing unsynced accounts on WordPress and Discourse use the Discourse login link on the WordPress login page.

The 'Login with Discourse' link on `wp-login.php` has some styles added to it that should be improved. Possibly they should be made optional.

I've added an optional redirect from `my-blog.com/login` to `my-blog.com/sso`.

I changed the nonce code so that the nonce is invalidated after it's used. There may be some problems with it.

**Comment by iamntz** [comment]
> I've added an option to sync existing accounts by email address.

I'm not sure if this is the correct way, maybe we should put this behind an option?

The reason of why this is wrong is that you will also need to hide/disable the email field in the user profile, otherwise will lead to user frustration (imagine that you change your email on a site just to see it changed back after you re-login)

**Comment by iamntz** [comment]
The main problem with transients is that you can't be sure that it will still be there in 10 minutes:

> Everyone seems to misunderstand how transient expiration works, so the long and short of it is: transient expiration times are a maximum time. There is no minimum age. Transients might disappear one second after you set them, or 24 hours, but they will never be around after the expiration time.

Transients may also might behave as wanted in a multisite environment (although i'm not sure that _my_ code will behave nice either)

Also, you assume that a site will have `mod_rewrite` enabled, which may or may not be true.

---

I think that your proposed changes are a bit of overwork since we only need to deal with the „login by url” thingy, that will generate a nonce dynamcially (instead of how it works at this moment).

**Comment by scossar** [comment]
> The main problem with transients is that you can't be sure that it will still be there in 10 minutes

Thanks! That won't work then. The same idea can be made to work with options - it's just a little more work to expire them.

**Comment by iamntz** [comment]
> The same idea can be made to work with options

I'm not sure that I understand what's wrong with the way [I implemented](https://github.com/discourse/wp-discourse/pull/257/commits/9670d8048866d94c17153250fa7924050b1d89c5#diff-20f931cb30a44765f3c26d6ea4702bc5R153): it's basically the same implementation as WordPress uses, with a shorter lifespan.

**Comment by scossar** [comment]
The issue is that it's not expired after it's used. A WordPress nonce isn't really a nonce (number used once.) I don't know how big of a concern this is though.

**Comment by iamntz** [comment]
Well, as long as the whole WP backend uses nonces that are usually valid way more than 10 minutes (by default is one day) I'm not sure we should worry about this:

> By default, a nonce has a lifetime of one day. After that, the nonce is no longer valid even if it matches the action string. To change the lifetime, add a nonce_life filter specifying the lifetime in seconds.

https://codex.wordpress.org/WordPress_Nonces#Modifying_the_nonce_lifetime

**Comment by scossar** [comment]
The problem I'm seeing with not expiring the nonce is that a URL is being saved in my browser's history that can be used by anyone to login to my WordPress site as me for a period of 10 minutes. This is true even after I've logged out of both Discourse and WordPress.

**Comment by iamntz** [comment]
What about an extra mysql table with two columns: nonce & expiration. When it's used, it's also deleted.

**Comment by scossar** [comment]
Yes, something like that will work. Have a look at this and see if it makes
sense.
https://github.com/scossar/wp-discourse/blob/beta-external-sso/lib/simple-nonce.php
It adds an option where the option name is the nonce and the value is the
expiry time.

**Comment by iamntz** [comment]
Alright, so here is what changed:

1. Added truly unique nonces, that are generated, stored into db and wiped if valid as soon as they are used;
1. Renamed hooks to a closer to reality name. Eg. `'discourse/sso/provider/redirect_after_failed_login'` => `'discourse/sso/client/redirect_after_failed_login'` (provider -> client)
1. Added Composer's autoload so it will load classes & files automatically (also moved all the `require` to composer.json)
1. SSO Client class is autoloaded (if/after this PR is merged i'm planning to move all classes to autoload)

Hope i didn't forgot something :)

**Comment by scossar** [comment]
Thanks! I'll check it out.

Are you sure you need to create a database table for the nonces?

> Added Composer's autoload so it will load classes & files automatically (also moved all the require to composer.json)

That's great!

**Comment by iamntz** [comment]
> Are you sure you need to create a database table for the nonces?

Not really actually :D 

But using options isn't really an _option_ either, because we need a datetime field (or an `int`) so I could quickly diff between NOW and NOW-600seconds.

**Comment by scossar** [comment]
It's really good! A few issues:

- When a user is synced with Discourse, there should probably be a check to make sure that the correct user is being synced. If there are different users logged into WordPress and Discourse, the 'discourse_sso_user_id' will be set to the wrong user. In `update_user` you could check that the WordPress `user_login` for the ID matches `$query['username]`. If they don't match, some kind of notice could be given to the user telling them that they are probably logged into Discourse as a different user.

- Some of the functions in the shortcode file seem like they could be somewhere else. For example, `get_discourse_link_markup` is used in `sso-login-form.php`. That's a minor detail and could be changed later.

- Unless there's a good reason to do it, don't alter the plugin's naming convention for class files and WordPress hooks.

- I really like the autoloader, but I'm not sure how it's going to work with people installing the plugin from the WordPress plugin repo.

**Comment by scossar** [comment]
It seems to me that it should be safe to commit `vendor/` to git. There are some possible issues with using Composer packages in WordPress plugins: https://wptavern.com/a-narrative-of-using-composer-in-a-wordpress-plugin

If you want to rename the class files so that they work with the PRS-4 autoloader, go ahead and do it.

**Comment by iamntz** [comment]
> When a user is synced with Discourse, there should probably [...]

But we should enforce the same username on both platforms?

>Unless there's a good reason to do it, don't alter the plugin's naming convention for class files and WordPress hooks.

I think you figured out why I changed the class names and it seems to like this way. Let me explain the filters.

Having a filter like this: `discourse/sso/client/redirect_after_login` makes it more readable and... namespaced, if you want. At first sight, you understand that this is from `discourse` package, `sso` module, `client` functionality. 

Now compare this with `discourse_sso_client_redirect_after_login`. What is this all about? Is the `sso_client_redirect` that will happen `after_login` ? Or is the `sso_client` module_client that will do a `redirect_after_login`?

We could use other naming structure? Sure, we could use double underscore to _separate_ sections, but I really think that this won't improve the readability as good as slashing parts.

> If you want to rename the class files so that they work with the PRS-4 autoloader

But we should deal with _all_ classes, not only this one, otherwise the autoloader is kind of useless.

**Comment by scossar** [comment]
> But we should enforce the same username on both platforms?

I'm not sure. There's no perfect solution for this. Possibly you could check if either the username **or** the email matches?

I'm fine with changing the naming convention for filters, and what you propose makes sense to me. If it's going to be changed it has to be done with the goal of eventually making the change consistent across the whole plugin.

> But we should deal with all classes

Yes, if you want to make that change in this PR, that would be great.

**Comment by iamntz** [comment]
> I'm not sure. There's no perfect solution for this. Possibly you could check if either the username or the email matches?

I'm pushing in a minute this flow 

- If WP user is guest, then auth to match the Discourse user;
- If WP user is auth but not linked to any Discourse user, then match to the Discourse user;
- If WP user is auth AND linked to Discourse, then either redirect to home (or whatever the `redirect_to` param is set to) or display an error.

I'm very undecided between redirect (with no message whatsoever and error display), but I think redirecting without any message is somehow more practical (i.e. users can't easily find the auth url if they are logged in;)

> Yes, if you want to make that change in this PR, that would be great.

Not really, this is quite a bit of working to do that will change most existing files and it's not really related to SSO functionality. I'll open another PR soon after this one, but you should consider my thoughts on #260 as well.

**Comment by iamntz** [comment]
> has to be done with the goal of eventually making the change consistent across the whole plugin.

Sure. One of the reasons of introducing this way of writing hooks is that there are very few _existing_ hooks. Looking for a way of deprecating this and I'll create a new PR for this as well.

**Comment by scossar** [comment]
It's looking good, but there are still a few issues - `handle_errors` doesn't exit after the redirect, so the login error messages aren't seen by the user. `update_user` isn't returning anything, so if there's an error in updating the user, `handle_errors` isn't called. Also, if there's an error in updating the user, the `sso_meta_key` is being updated for the (probably) wrong user. The `sso_meta_key` should probably not be updated once it has been set - it also shouldn't be updated if `wp_update_user` returns an error. `auth_user` needs to call `exit` after redirecting the user - this keeps the sso parameters from being printed in the address bar after authentication. An error code and message needs to be added for 'existing_user_login' - that seems to be the easiest error to get.

I'm going to make the changes to fix these issues and then merge this into the beta branch on my local computer - hopefully early tomorrow.

Thanks for all your work on this!

**Comment by scossar** [comment]
This is merged now. Thanks!

**Comment by erlend-sh** [comment]
@iamntz & @scossar Major thanks to the both of you for this doozy of a PR. Obviously a lot of time went into the code, but you also dedicated ample time to communicating your ideas and challenges.

No matter how well-intentioned both parties are, I've seen this type of technical debate devolve into an unproductive timesink more times than I care to count, so **major kudos to the both of you for keeping things constructive and civil!** 💯

**Pull request merged**
