### PR TITLE
Add a log entry when HTTP request fails

### PR DESCRIPTION
**Pull request by nigelbabu**
This will handle the failure gracefully while not completely hiding debugging information.

### CODE REVIEW

**Comment by retlehs** [comment]
nice, thank you! this is long overdue 👍

**Comment by nigelbabu** [comment]
@retlehs Can you merge this in if it looks good? :)

**Comment by retlehs** [comment]
yes sir. just got back from holiday and getting caught up!

**Comment by nigelbabu** [comment]
Thank you!

**Pull request merged**
