### PR TITLE
Bump version to 2.2.4

### PR DESCRIPTION
**Pull request by scossar**
This PR adds a logging system and a test suite to the plugin.

### CODE REVIEW

**Comment by LeoColomb** [comment]
@scossar @angusmcleod This PR add an interesting feature but breaks few stuff, the most critical one is composer usage.
Is there a need to include vendor files inside the repo? (this is not recommended...)

Thx! 🙂

**Comment by angusmcleod** [comment]
Hey @LeoColomb, is there a specific issue you wish to report?

We've explained the approach to using composer packages, which is used by a number of other large Wordpress plugins, in detail here: https://github.com/discourse/wp-discourse/blob/master/docs/COMPOSER.md

You can see this version being used on a wordpress instance manage by composer here: https://composer.wordpress.thepavilion.io.

**Comment by LeoColomb** [comment]
@angusmcleod Thanks for the answer!

> We've explained the approach to using composer packages

Why is this approach not standard for Composer?

> instance managed by composer here: [composer.wordpress.thepavilion.io](https://composer.wordpress.thepavilion.io).

Cool! Would it be possible to see the config used for that deployment?

**Comment by angusmcleod** [comment]
The approach is standard for composer, as far as using the package is concerned. Please note the following in the docs:

> Please note, this guide is intended for developers of this plugin. If you're using this plugin via composer, this does not apply to you. Use it as you normally would.

You can see the full config of [composer.wordpress.thepavilion.io](https://composer.wordpress.thepavilion.io) [here](https://github.com/paviliondev/spinupwp-composer-site). Note that the relevant part for ``wp-discourse`` is just a normal composer require:

```
"discourse/wp-discourse": "*"
```

The v2.2.4 changes do not affect normal usage of ``discourse/wp-discourse`` as a composer package.

**Comment by angusmcleod** [comment]
#406 is not necessary for composer to work. That was made for other reasons. As mentioned, the approach, and the other folks who use it (e.g. Yoast and Delicious Brains), is explained in COMPOSER.md. We could perhaps debate the theory of this more, but this might be the best place to do it :) If you have a specific issue to report, please make a post in https://meta.discourse.org/c/support/wordpress/21 and we can discuss it. Thanks for taking an interest though :+1:

**Pull request merged**
