### PR TITLE
WIP: 1.0.0 release

### PR DESCRIPTION
**Pull request by scossar**
Todo:
- improve default html templates (mainly `participant_html`)
- update `CHANGELOG.md`
- try to tweak `travis.yml` and `codesniffer.ruleset.xml` so that the tests can pass
...

This should be ready to go in the next couple of days.

screenshot 2016-09-15 20 53 11

screenshot 2016-09-15 20 55 05

screenshot 2016-09-15 20 55 29

screenshot 2016-09-15 20 55 51

screenshot 2016-09-15 20 56 36

screenshot 2016-09-15 20 57 31

### CODE REVIEW

**Comment by scossar** [comment]
More for the todo list:
- fallback to displaying the username in the comments template if the user's full name is not available
- move WooCommerce into a separate plugin and also write some example code that can be added to a theme's `functions.php` file to support WooCommerce without installing an extra plugin
- write a wp-cli script and/or database query that can be used to mark email addresses as `discourse_email_not_verified` for sites that have pre-existing users with unverified email addresses
- test the upgrade procedure from different versions of the plugin

**Comment by retlehs** [comment]
just wanted to say that this is looking really good! nice job on the admin interface updates :+1:

**Comment by scossar** [comment]
I've added a configurable-text-content setting.

screenshot 2016-09-20 12 58 39

screenshot 2016-09-20 12 59 41

**Comment by scossar** [comment]
Todo: stop filtering the value from the `comments_number` hook, except for when there are both Discourse and WordPress comments on a post. For most cases it should be good enough to filter count that's passed to the `get_comments_number` filter. If there are only Discourse comments, or only WordPress comments, the filtered number will be used by WordPress in it's `comments_number` function to return the correct language string for the number.

**Pull request merged**
