### PR TITLE
DRY-ness settings validator

### PR DESCRIPTION
**Pull request by iamntz**
So basically I did this:

1. combined all validators for a bunch of fields into only one;
1. simplified some conditionals

### CODE REVIEW

**Comment by scossar** [comment]
The idea is good. I started doing this in the last update with the checkbox inputs.

When I try to update any text on the 'text content' tab using your PR, I get the warning,  `call_user_func_array() expects parameter 1 to be a valid callback, cannot access protected method WPDiscourse\Validator\SettingsValidator::sanitize_text()`. The content of all the inputs on that tab is then deleted.

**Comment by scossar** [comment]
Most of these changes have already been made here: https://github.com/discourse/wp-discourse/pull/264
If you want to help with the work on that branch, that would be great. I can give you some details about what's going on with it tomorrow.

**Comment by iamntz** [comment]
> The idea is good. I started doing this in the last update with the checkbox inputs.

Yeah, I saw you started a some stuff, but when I searched, it was nothing there on validator :)

Btw, maybe you could split that PR into multiple parts? E.g. moving/renaming classes in one PR, simplifying/extracting methods another PR and so on?

**Comment by scossar** [comment]
Something similar to this has already been finished and will be included in the next update.

**Pull request closed without merging**
